### PR TITLE
feat: upgrade to Palm

### PR DESCRIPTION
**Pull request by regisb**

### CODE REVIEW

**Comment by regisb** [comment]
This does not work and I have no idea why: https://mobile.palm.demo.overhang.io/app.apk
The app simply crashes on launch on my phone. I could definitely use some help.

**Comment by cmltaWt0** [comment]
I've managed to get the app working with Demo Palm only on [release/3.1.4](https://github.com/openedx/edx-app-android/tree/release/3.1.4).

Actually it works up to this commit ([Merge pull request #1684 from openedx/hamza/LEARNER-8810](https://github.com/openedx/edx-app-android/commit/046a0277e8c428193d8d5711a5d1aac3a9626731)) but it's better to use the release tag (3.1.4).

The issue firstly introduced in https://github.com/openedx/edx-app-android/commit/ae20f10a9cfc864b22dd2560884851b8649257e2

Exception details:
https://gist.github.com/cmltaWt0/f6a9e52522c08f0701733833c01c7dcc

**Comment by regisb** [comment]
This is suuuuuper useful information @cmltaWt0, thank you so much! How did you generate the exception details? I wish I could generate the logs myself, that would be tremendously useful to test the app and report issues upstream.

**Comment by cmltaWt0** [comment]
@regisb I did it through the local build in Android Studio :)

image

**Comment by cmltaWt0** [comment]
@regisb could you update me about rebuilding this on palm demo with new tag to test? I just want to re-test and close the https://github.com/openedx/wg-build-test-release/issues/263

**Comment by regisb** [comment]
I did rebuild the image and deploy it again. ~~This time, I am not even able to install the app on my phone...~~ IT WORKS!

**Pull request closed without merging**
